### ISSUE TITLE
Build Broken

### ISSUE THREAD

**Issue by chkelly** [andrewgaul/s3proxy#133]
Looks like some updates to the jclouds 2.0 snapshot may have broken this projects ability to build.

```
Downloaded: https://repo.maven.apache.org/maven2/com/google/collections/google-collections/1.0/google-collections-1.0.jar (625 KB at 134.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_core/2.0.5/error_prone_core-2.0.5.jar (3574 KB at 578.4 KB/sec)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /opt/s3proxy/target/classes
/root/.m2/repository/org/apache/jclouds/driver/jclouds-slf4j/2.0.0-SNAPSHOT/jclouds-slf4j-2.0.0-SNAPSHOT.jar(org/jclouds/logging/slf4j/config/SLF4JLoggingModule.class): warning: Cannot find annotation method 'value()' in type 'AutoService': class file for com.google.auto.service.AutoService not found
1 warning
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ s3proxy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ s3proxy ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /opt/s3proxy/target/test-classes
/root/.m2/repository/org/apache/jclouds/driver/jclouds-slf4j/2.0.0-SNAPSHOT/jclouds-slf4j-2.0.0-SNAPSHOT.jar(org/jclouds/logging/slf4j/config/SLF4JLoggingModule.class): warning: Cannot find annotation method 'value()' in type 'AutoService': class file for com.google.auto.service.AutoService not found
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar(com/google/common/util/concurrent/Monitor.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
10 warnings
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ s3proxy ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit47/2.19.1/surefire-junit47-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit47/2.19.1/surefire-junit47-2.19.1.pom (7 KB at 67.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.19.1/surefire-providers-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-providers/2.19.1/surefire-providers-2.19.1.pom (3 KB at 34.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit48/2.19.1/common-junit48-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit48/2.19.1/common-junit48-2.19.1.pom (4 KB at 40.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit4/2.19.1/common-junit4-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit4/2.19.1/common-junit4-2.19.1.pom (3 KB at 28.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit3/2.19.1/common-junit3-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit3/2.19.1/common-junit3-2.19.1.pom (2 KB at 24.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/2.19.1/surefire-api-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/2.19.1/surefire-api-2.19.1.pom (4 KB at 50.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/2.19.1/common-java5-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/2.19.1/common-java5-2.19.1.pom (3 KB at 34.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.pom (7 KB at 98.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/21/maven-shared-components-21.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/21/maven-shared-components-21.pom (5 KB at 84.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/25/maven-parent-25.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/25/maven-parent-25.pom (37 KB at 487.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom (15 KB at 225.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/2.19.1/surefire-grouper-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/2.19.1/surefire-grouper-2.19.1.pom (3 KB at 44.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/2.19.1/surefire-testng-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/2.19.1/surefire-testng-2.19.1.pom (3 KB at 39.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/2.19.1/surefire-testng-utils-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/2.19.1/surefire-testng-utils-2.19.1.pom (3 KB at 46.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/2.19.1/maven-surefire-common-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/2.19.1/maven-surefire-common-2.19.1.pom (8 KB at 105.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.pom (2 KB at 24.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-tools/3.3/maven-plugin-tools-3.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-tools/3.3/maven-plugin-tools-3.3.pom (13 KB at 162.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/2.19.1/surefire-booter-2.19.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/2.19.1/surefire-booter-2.19.1.pom (4 KB at 41.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom (3 KB at 39.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom (10 KB at 136.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/16/maven-parent-16.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/16/maven-parent-16.pom (23 KB at 315.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom (17 KB at 236.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit47/2.19.1/surefire-junit47-2.19.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit48/2.19.1/common-junit48-2.19.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit4/2.19.1/common-junit4-2.19.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit3/2.19.1/common-junit3-2.19.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit4/2.19.1/common-junit4-2.19.1.jar (26 KB at 138.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/2.19.1/surefire-grouper-2.19.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit3/2.19.1/common-junit3-2.19.1.jar (12 KB at 60.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/2.19.1/surefire-testng-2.19.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-junit48/2.19.1/common-junit48-2.19.1.jar (23 KB at 105.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/2.19.1/common-java5-2.19.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.9/maven-shared-utils-0.9.jar (168 KB at 738.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/2.19.1/surefire-testng-utils-2.19.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng/2.19.1/surefire-testng-2.19.1.jar (42 KB at 140.5 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-grouper/2.19.1/surefire-grouper-2.19.1.jar (38 KB at 127.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/2.19.1/maven-surefire-common-2.19.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/2.19.1/surefire-booter-2.19.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit47/2.19.1/surefire-junit47-2.19.1.jar (150 KB at 497.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/common-java5/2.19.1/common-java5-2.19.1.jar (44 KB at 132.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-testng-utils/2.19.1/surefire-testng-utils-2.19.1.jar (27 KB at 66.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar (11 KB at 22.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/2.19.1/surefire-api-2.19.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/2.19.1/surefire-booter-2.19.1.jar (45 KB at 94.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/maven-surefire-common/2.19.1/maven-surefire-common-2.19.1.jar (286 KB at 529.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.jar (14 KB at 20.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/2.19.1/surefire-api-2.19.1.jar (192 KB at 265.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar (309 KB at 426.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar (223 KB at 289.3 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.gaul.s3proxy.S3ProxyTest
Tests run: 20, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 10.975 sec - in org.gaul.s3proxy.S3ProxyTest
Running org.gaul.s3proxy.S3AwsSdkTest
Tests run: 10, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 5.851 sec <<< FAILURE! - in org.gaul.s3proxy.S3AwsSdkTest
testUnicodeObject(org.gaul.s3proxy.S3AwsSdkTest)  Time elapsed: 3.542 sec  <<< ERROR!
com.amazonaws.services.s3.model.AmazonS3Exception: java.io.IOException: Content-Length mismatch, actual: 1 expected: 173 (Service: Amazon S3; Status Code: 500; Error Code: 500 java.io.IOException: Content-Length mismatch, actual: 1 expected: 173; Request ID: null)
	at org.gaul.s3proxy.S3AwsSdkTest.testUnicodeObject(S3AwsSdkTest.java:392)

testAwsV4Signature(org.gaul.s3proxy.S3AwsSdkTest)  Time elapsed: 2.209 sec  <<< ERROR!
com.amazonaws.services.s3.model.AmazonS3Exception: java.io.IOException: Content-Length mismatch, actual: 1 expected: 173 (Service: Amazon S3; Status Code: 500; Error Code: 500 java.io.IOException: Content-Length mismatch, actual: 1 expected: 173; Request ID: null)
	at org.gaul.s3proxy.S3AwsSdkTest.testAwsV4Signature(S3AwsSdkTest.java:164)

testMultipartCopy(org.gaul.s3proxy.S3AwsSdkTest)  Time elapsed: 2.193 sec  <<< ERROR!
com.amazonaws.services.s3.model.AmazonS3Exception: java.io.IOException: Content-Length mismatch, actual: 1 expected: 173 (Service: Amazon S3; Status Code: 500; Error Code: 500 java.io.IOException: Content-Length mismatch, actual: 1 expected: 173; Request ID: null)
	at org.gaul.s3proxy.S3AwsSdkTest.testMultipartCopy(S3AwsSdkTest.java:272)

testUpdateBlobXmlAcls(org.gaul.s3proxy.S3AwsSdkTest)  Time elapsed: 2.181 sec  <<< ERROR!
com.amazonaws.services.s3.model.AmazonS3Exception: java.io.IOException: Content-Length mismatch, actual: 1 expected: 173 (Service: Amazon S3; Status Code: 500; Error Code: 500 java.io.IOException: Content-Length mismatch, actual: 1 expected: 173; Request ID: null)
	at org.gaul.s3proxy.S3AwsSdkTest.testUpdateBlobXmlAcls(S3AwsSdkTest.java:370)


Results :

Tests in error:
  S3AwsSdkTest.testAwsV4Signature:164 » AmazonS3 java.io.IOException: Content-Le...
  S3AwsSdkTest.testMultipartCopy:272 » AmazonS3 java.io.IOException: Content-Len...
  S3AwsSdkTest.testUnicodeObject:392 » AmazonS3 java.io.IOException: Content-Len...
  S3AwsSdkTest.testUpdateBlobXmlAcls:370 » AmazonS3 java.io.IOException: Content...

Tests run: 30, Failures: 0, Errors: 4, Skipped: 1


-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Tests run: 129, Failures: 19, Errors: 0, Skipped: 15, Time elapsed: 15.169 sec <<< FAILURE! - in TestSuite
testCopyBlobCopyMetadata(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.024 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testCopyBlobReplaceMetadata(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.018 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testCopyIfMatch(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.016 sec  <<< FAILURE!
org.jclouds.aws.AWSResponseException: request PUT http://127.0.0.1:48348/root-blobstore-7491571079735849768/to HTTP/1.1 failed with code 501, error: AWSError{requestId='4442587FB7D0A2F9', requestToken='null', code='NotImplemented', message='A header you provided implies functionality that is not implemented.'}

testCopyIfMatchNegative(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.019 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[412]> but was:<[501]>

testCopyIfModifiedSince(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.015 sec  <<< FAILURE!
org.jclouds.aws.AWSResponseException: request PUT http://127.0.0.1:48348/root-blobstore0/to HTTP/1.1 failed with code 501, error: AWSError{requestId='4442587FB7D0A2F9', requestToken='null', code='NotImplemented', message='A header you provided implies functionality that is not implemented.'}

testCopyIfModifiedSinceNegative(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.03 sec  <<< FAILURE!
java.lang.AssertionError:

Expecting:
 <501>
to be in:
 <[304, 412]>


testCopyIfNoneMatch(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.019 sec  <<< FAILURE!
org.jclouds.aws.AWSResponseException: request PUT http://127.0.0.1:48348/root-blobstore835184202432871548/to HTTP/1.1 failed with code 501, error: AWSError{requestId='4442587FB7D0A2F9', requestToken='null', code='NotImplemented', message='A header you provided implies functionality that is not implemented.'}

testCopyIfNoneMatchNegative(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.017 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[412]> but was:<[501]>

testCopyIfUnmodifiedSince(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.018 sec  <<< FAILURE!
org.jclouds.aws.AWSResponseException: request PUT http://127.0.0.1:48348/root-blobstore-5890954602574779503/to HTTP/1.1 failed with code 501, error: AWSError{requestId='4442587FB7D0A2F9', requestToken='null', code='NotImplemented', message='A header you provided implies functionality that is not implemented.'}

testCopyIfUnmodifiedSinceNegative(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.018 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[412]> but was:<[501]>

testMultipartUploadMultipleParts(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 1.052 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testMultipartUploadSinglePart(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.022 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testPutByteSource(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.01 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testPutInputStream(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.01 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testPutMultipartByteSource(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 6.413 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testPutMultipartInputStream(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.47 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testPutObject(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.017 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testPutObject(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.025 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>

testPutObject(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)  Time elapsed: 0.013 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"max-age=3600"> but was:<null>


Results :

Failed tests:
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyBlobCopyMetadata:895->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyBlobReplaceMetadata:944->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfMatch:967 » AWSResponse
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfMatchNegative:1001 expected:<[412]> but was:<[501]>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfModifiedSince:1082 » AWSResponse
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfModifiedSinceNegative:1119
Expecting:
 <501>
to be in:
 <[304, 412]>

  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfNoneMatch:1024 » AWSResponse
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfNoneMatchNegative:1058 expected:<[412]> but was:<[501]>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfUnmodifiedSince:1143 » AWSResponse
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testCopyIfUnmodifiedSinceNegative:1178 expected:<[412]> but was:<[501]>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testMultipartUploadMultipleParts:1272->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testMultipartUploadSinglePart:1234->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testPutByteSource:627->BaseBlobIntegrationTest.testPut:757->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testPutInputStream:635->BaseBlobIntegrationTest.testPut:757->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testPutMultipartByteSource:650->BaseBlobIntegrationTest.testPut:757->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testPutMultipartInputStream:658->BaseBlobIntegrationTest.testPut:757->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest.testPutObject(org.gaul.s3proxy.JcloudsS3BlobIntegrationLiveTest)
  Run 1: JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testPutObject:585->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  Run 2: JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testPutObject:585->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>
  Run 3: JcloudsS3BlobIntegrationLiveTest>BaseBlobIntegrationTest.testPutObject:585->BaseBlobIntegrationTest.checkContentMetadata:769->BaseBlobIntegrationTest.checkCacheControl:785 expected:<"max-age=3600"> but was:<null>


Tests run: 127, Failures: 17, Errors: 0, Skipped: 15

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:05 min
[INFO] Finished at: 2016-03-24T15:17:21+00:00
[INFO] Final Memory: 37M/372M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project s3proxy: There are test failures.
[ERROR]
[ERROR] Please refer to /opt/s3proxy/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c mvn package' returned a non-zero code: 1
```

**Comment by andrewgaul** [comment]
@chkelly I cannot reproduce your symptoms.  Can you update your S3Proxy checkout via `git fetch` and `git rebase` and test again?

**Comment by chkelly** [comment]
My guess is that its getting it from your local build cache.

Can you try it in a situation where you are pulling down all your artifacts fresh?

**Comment by andrewgaul** [comment]
I removed all jclouds artifacts via:

```
find .m2/repository/org/apache/jclouds/ -name 2.0.0-SNAPSHOT | xargs rm -r
```

Can you confirm that you are using the latest commit, 8b2a869341f3b5bb5e7fb23e89ab6cedb8802b69, via `git show`?

**Comment by chkelly** [comment]
ugh. Terribly sorry, I was using https://github.com/ritazh/s3proxydocker as a base for trying to get a container built. I just noticed he forked your repo and references that in the dockerfile (but didn't make any changes).

 
Great project by the way :)

**Comment by andrewgaul** [comment]
@chkelly I am looking at providing a standard Dockerfile with S3Proxy.  See #123.

@ritazh You should rebase your S3Proxy fork to track some jclouds 2.0.0-SNAPSHOT changes.

**Comment by ritazh** [comment]
Thanks for spotting this issue! Sorry if my dockerfile is causing confusion. I have updated it to point to the master of this repo. [new commit](https://github.com/ritazh/s3proxydocker/commit/30abfd6d731d461c12a296c313e41c95353f93d2)
