### ISSUE TITLE
Return a more coherent error if Transfer-Encoding: chunked is set

### ISSUE THREAD

**Issue by timuralp** [andrewgaul/s3proxy#134]
AWS S3 v2 signature method does not allow for chunked uploads (setting Transfer-Encoding: chunked). I discovered (through the virtue of a buggy library), that submitting a chunked request to S3Proxy results in:
```
W 05-05 17:27:54.408 S3Proxy-17 o.e.jetty.http.HttpParser:1355 |::] badMessage: java.lang.NumberFormatException: !hex 35 for HttpChannelOverHttp@6245f4b9{r=4,c=false,a=DISPATCHED,uri=/timur-test/AUTH_test/test/-bash_logout}
W 05-05 17:27:54.411 S3Proxy-17 o.e.jetty.server.HttpChannel:396 |::] /timur-test/AUTH_test/test/-bash_logout
java.lang.IllegalStateException: s=DISPATCHED i=true a=null
	at org.eclipse.jetty.server.HttpChannelState.handling(HttpChannelState.java:232)
	at org.eclipse.jetty.server.HttpChannel.badMessage(HttpChannel.java:724)
	at org.eclipse.jetty.server.HttpConnection$HttpChannelOverHttp.badMessage(HttpConnection.java:529)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1362)
	at org.eclipse.jetty.server.HttpConnection.parseContent(HttpConnection.java:305)
	at org.eclipse.jetty.server.HttpInputOverHTTP.nextContent(HttpInputOverHTTP.java:90)
	at org.eclipse.jetty.server.HttpInputOverHTTP.nextContent(HttpInputOverHTTP.java:31)
	at org.eclipse.jetty.server.HttpInput.getNextContent(HttpInput.java:143)
	at org.eclipse.jetty.server.HttpInputOverHTTP.blockForContent(HttpInputOverHTTP.java:69)
	at org.eclipse.jetty.server.HttpInput$1.waitForContent(HttpInput.java:489)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:122)
	at com.google.common.hash.HashingInputStream.read(HashingInputStream.java:65)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:175)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:220)
	at org.jclouds.blobstore.TransientStorageStrategy.putBlob(TransientStorageStrategy.java:167)
```

S3Proxy should return a 501 error with the XML stating that the method is not implemented in such cases. I'll try to submit a PR for that.

**Comment by timuralp** [comment]
Reference: https://forums.aws.amazon.com/message.jspa?messageID=561616

**Comment by gaul** [comment]
S3Proxy still lacks support for this: https://github.com/gaul/s3-tests/blob/1871a5ed353eee7a65a1c665f49962e0f6d54760/s3tests_boto3/functional/test_s3.py#L1630

**Comment by gaul** [comment]
Retitled: the error this asked for is no longer the right answer, and the incoherent one it reported is gone.

**The reported symptom is fixed.** The `NumberFormatException: !hex` and the `IllegalStateException` out of `HttpChannel.badMessage` came from Jetty 9 and jclouds, neither of which is still here. On current master a chunked PUT is refused cleanly:

| request | response |
| --- | --- |
| `Transfer-Encoding: chunked`, no `Content-Length` | 411 `<Code>MissingContentLength</Code>`, S3-shaped XML |
| `Transfer-Encoding: chunked` **and** `Content-Length: 3` | 200, and a GET returns exactly the 3 bytes |
| neither header | 411 `MissingContentLength`, as S3 answers |

Note the middle row: a client that sends both is already served correctly, chunks decoded, no truncation or corruption. The gap is only a body with no declared length at all.

**The 501 this asked for would now be wrong.** That request rested on a 2016 forum post saying S3 refuses chunked uploads. S3 accepts them today, and the upstream test asserts a 200:

```python
@pytest.mark.fails_on_s3proxy
def test_object_write_with_chunked_transfer_encoding():
    client.meta.events.register_first('before-sign.*.*', _ev_add_te_header)
    response = client.put_object(Bucket=bucket_name, Key='foo', Body='bar')
    assert response['ResponseMetadata']['HTTPStatusCode'] == 200
```

Run against master with `--runxfail`, it still fails with `MissingContentLength`. Answering 501 would move further from S3 rather than closer.

**What support would take.** `S3ProxyHandler` requires the header for PutObject and for UploadPart, then hands the value to `builder.contentLength(...)`. That is not a formality: the S3, Azure and GCS backends need a size up front to stream a body upstream. Accepting a length-less body means buffering it, to memory or to a temp file, or turning it into a multipart upload underneath. The nio2 and filesystem backends could stream it as it arrives. So this is a design decision about where to put the bytes, which is presumably why it has sat this long.

Unchanged in substance since #134 was filed -- only the shape of the remedy has.

**Comment by gaul** [comment]
On whether the backends can support this: three of the five already do. What each `putBlob` needs at its SDK boundary:

| backend | accepts unknown length today | evidence |
| --- | --- | --- |
| nio2 (transient + filesystem) | yes | streams through a `HashingInputStream` into a temp file and moves it; the length is never consulted |
| azureblob | yes, already implemented | an explicit `contentLength == null` branch uses `BlockBlobOutputStreamOptions` with `getBlobOutputStream`, staging blocks as bytes arrive |
| gcloudsdk | yes | `storage.createFrom(blobInfo, is, opts)` takes no length and does a resumable upload |
| openstackswift | probably | `Payloads.create(is)`, and `putBlob` never names a `Content-Length`; openstack4j would send it chunked, which Swift accepts natively. Not verified against a live Swift |
| awssdk | no, deliberately | `throw new IllegalArgumentException("Content-Length is required for S3 putBlob")`, commented "Reject unknown length instead of crashing memory" |

`ContentMetadata.contentLength` is already `@Nullable`, and the Azure backend branches on exactly that, so the interface tolerates this today.

**The uniform fix is in the handler, not in the backends.** Buffering the body in `S3ProxyHandler` turns an unknown length into a known one before `putBlob` is called, which works for every backend including the S3 one. That machinery already exists -- SigV4 requests that need a payload digest do it:

```java
// buffer the entire stream to calculate digest
payload = ByteStreams.limit(is, v4MaxNonChunkedRequestSize + 1).readAllBytes();
if (payload.length == v4MaxNonChunkedRequestSize + 1) {
    throw new S3Exception(S3ErrorCode.MAX_MESSAGE_LENGTH_EXCEEDED);
}
```

Reusing it for a chunked body brings the bound, the config property and the error code for exceeding it along with it, and needs no backend change at all. `test_object_write_with_chunked_transfer_encoding` uploads three bytes, so it would pass on that alone.

**The trade-off only appears above the threshold**, and it is memory against ETag fidelity:

* Escalate to an internal multipart upload. Every backend implements MPU, so one part-sized buffer replaces a whole-body one. But the object's ETag becomes `<md5>-<N>`, where S3 answers a chunked PUT with a plain MD5, so a client comparing ETags sees a difference S3 would not show.
* Spill to a temp file and PUT with the known length. Keeps the ETag exact, costs disk and a second pass.
* Cap it: buffer to the existing limit and answer `MaxMessageLengthExceeded` beyond, which is what the SigV4 path already does.

Buffering to a known length looks like the place to start: small, reuses what is there, fixes the test, touches no backend. Unbounded chunked streaming is worth treating as a separate question, and spill-to-disk keeps the ETag matching S3 where MPU would not.

**Comment by gaul** [comment]
Fixed by "Accept an upload framed with Transfer-Encoding: chunked".

`S3ProxyHandler` now reads a body that declared no length in order to learn one, before any backend is asked to store it, for both PutObject and UploadPart. Every backend is therefore handed a size it knows and none of them changed -- including the S3 one, which refuses a null length outright rather than buffer an unbounded body into the heap.

The read is bounded by `v4MaxNonChunkedRequestSize` and answers `MaxMessageLengthExceeded` past it, which are the bound and the error a SigV4 request whose payload must be digested already carried. An upload that framed its body neither way -- no length and no chunked framing -- still gets the 411 `MissingContentLength` that S3 sends.

Verified:

* `test_object_write_with_chunked_transfer_encoding` passes and its `fails_on_s3proxy` marker is gone.
* s3-tests transient-nio2: 288 passed, 0 failed. fake-gcs-server: 301 passed, 0 failed.
* New `TransferEncodingChunkedTest` covers a single chunk, several chunks, a chunked `UploadPart`, the 411 case, and the bound itself, the last by building a proxy with a 1 KiB limit and sending 2 KiB.

Two limits worth stating plainly, since this is the bounded version:

* A chunked body larger than the limit is refused rather than streamed. Supporting an arbitrarily large one means spilling to disk or turning it into a multipart upload underneath; of those, spill-to-disk is preferable because an internal MPU would give the object an `<md5>-<N>` ETag where S3 answers a chunked PUT with a plain MD5. Worth its own issue if anyone needs it.
* The buffering is per request, so concurrent chunked uploads can hold a multiple of the limit. That is the exposure the SigV4 digest path already carried; lowering `v4MaxNonChunkedRequestSize` bounds both.
