### ISSUE TITLE
Broken multipart upload on systems without extended attributes

### ISSUE THREAD

**Issue by auguster** [andrewgaul/s3proxy#135]
I build s3proxy from sources and whenever I try to upload a large file I get the following failure:
`A client error (Unknown) occurred when calling the CompleteMultipartUpload operation: Unknown`
The destination remains empty after that (even from hidden files).

**Comment by andrewgaul** [comment]
@auguster I need more information to diagnose your symptoms.  Can you re-run S3Proxy with: `java -DLOG_LEVEL=trace s3proxy` to get extended logging and share your properties file with me?  Also tell me how you issued a multipart upload, e.g., aws cli, s3cmd.

**Comment by auguster** [comment]
Sure, I was using aws cli to upload a file named `BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D`. I thought that the special character such as '%' could cause issues so I tried with 'normal' characters and I get the same error.

```
I 05-31 15:53:43.098 main org.eclipse.jetty.util.log:186 |::] Logging initialized @1989ms
I 05-31 15:53:43.182 main o.eclipse.jetty.server.Server:327 |::] jetty-9.2.z-SNAPSHOT
I 05-31 15:53:43.238 main o.e.j.server.ServerConnector:266 |::] Started ServerConnector@61df70d1{HTTP/1.1}{0.0.0.0:8080}
I 05-31 15:53:43.239 main o.eclipse.jetty.server.Server:379 |::] Started @2131ms
W 05-31 15:54:32.982 S3Proxy-14 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad81010-862d-49ba-a203-d4d2d4461363
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 15:54:33.711 S3Proxy-15 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad81010-862d-49ba-a203-d4d2d4461363
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 15:54:35.434 S3Proxy-17 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad81010-862d-49ba-a203-d4d2d4461363
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 15:54:38.361 S3Proxy-18 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad81010-862d-49ba-a203-d4d2d4461363
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 15:54:44.880 S3Proxy-13 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad81010-862d-49ba-a203-d4d2d4461363
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 16:29:58.032 S3Proxy-15 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad7494b-04ea-4b55-9014-5026e17df924
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 16:29:58.120 S3Proxy-18 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad7494b-04ea-4b55-9014-5026e17df924
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 16:29:59.141 S3Proxy-17 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad7494b-04ea-4b55-9014-5026e17df924
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 16:30:02.656 S3Proxy-16 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad7494b-04ea-4b55-9014-5026e17df924
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
W 05-31 16:30:08.338 S3Proxy-13 o.e.jetty.server.HttpChannel:396 |::] /preview/BWmK8%252Fj55FACyvu4wiUkfgFcy6WTyUmwHfOuEiOHxCA%253D?uploadId=6ad7494b-04ea-4b55-9014-5026e17df924
java.lang.NullPointerException: Null partETag
	at org.jclouds.blobstore.domain.AutoValue_MultipartPart.<init>(AutoValue_MultipartPart.java:20)
	at org.jclouds.blobstore.domain.MultipartPart.create(MultipartPart.java:29)
	at org.jclouds.blobstore.config.LocalBlobStore.listMultipartUpload(LocalBlobStore.java:874)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.listMultipartUpload(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCompleteMultipartUpload(S3ProxyHandler.java:1781)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:544)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:252)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by andrewgaul** [comment]
Are you running S3Proxy on Mac OS X?  S3Proxy uses extended attributes to store the ETag which java on Mac OS X does not support.  See https://github.com/andrewgaul/s3proxy/issues/6#issuecomment-53521257 and [JDK-8030048](https://bugs.openjdk.java.net/browse/JDK-8030048).

**Comment by auguster** [comment]
Not at all, I'm running s3proxy in a docker container on a Linux CoreOS. Release 1.4.0 works ok. It's generating a lot of temp and Example files. I remember that one of the 1.5.0 release (on OSS) worked as well but I don't recall which one. It was around November 2015. 

At that time, I was supposed to try s3proxy HTTP upload with acl but I stopped working on this project. I'm returning to s3proxy only now. But it might be for a short while, I'll be moving toward Swift storage instead of S3 soon.

**Comment by andrewgaul** [comment]
Are you using Docker with aufs?  If so can you use a bind mount as a workaround as suggested in docker/docker#1070?  Otherwise I will need to find another workaround for this.  Some have suggested storing these xattr in separate files which I could address in a few ways.  I could also weaken the checking in `LocalBlobStore.listMultipartUpload`.

**Comment by auguster** [comment]
It's docker with aufs but the persistent data of s3proxy is on a mounted folder from the host. But the folder itself is a NFS folder... The strange thing is that older version of s3proxy (for example 1.4.0) works.

Shouldn't the docker issue be present on those older version ?

**Comment by andrewgaul** [comment]
I rewrote multipart upload in 1.5.0 to better map onto the storage backend APIs, vastly improving performance for remote backends.  This work included new sanity checks to check ETags which you have encountered.  S3Proxy uses extended attributes to store ETags and unfortunately NFS does not appear to support them.  I will weaken the sanity checks when the filesystem does not support xattr.

**Comment by auguster** [comment]
I confirm that I can now upload with multipart. However whenever I do that, an empty file is created next to the uploaded file. For example `23192e74-e585-4420-97ce-eb7ce4b5de29`. This file is not deleted when the uploaded file gets deleted.

Those empty file are not found when multipart upload is not used.

**Comment by andrewgaul** [comment]
@auguster Thanks for the feedback!  The latest commit removes this stub blob.

**Comment by Riprock** [comment]
I'm seeing a problem with extended attributes when _reading_ from a share with Docker for Mac—which explicitly does not support extended attributes. Is this related, should this work?

**Comment by andrewgaul** [comment]
@Riprock Can you share your symptoms and open a new issue?

**Comment by Riprock** [comment]
Here you go #155.
