### ISSUE TITLE
boto3  client.list_objects fails with botocore.exceptions.ClientError when using against s3proxy

### ISSUE THREAD

**Issue by chicagobuss** [andrewgaul/s3proxy#137]
Not sure if I'm missing something obvious, but the same code works fine against 'the real s3'... Steps to reproduce:

```
import boto3

session = boto3.session.Session(aws_access_key_id='access', aws_secret_access_key='supersecret')
config = boto3.session.Config(s3={'addressing_style': 'path'})

# low level S3 client
client = session.client('s3', endpoint_url='http://localhost:5000', config=config)

# List Keys
for key in client.list_objects(Bucket='mahbucket')['Contents']:
    print key
```

Stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 548, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NotImplemented) when calling the ListObjects operation: A header you provided implies functionality that is not implemented.
```

**Comment by timuralp** [comment]
@chicagobuss can you add this line and re-run the request: `boto3.set_stream_logger('')`? This will enable boto3 debug output to see what headers are actually submitted.

**Comment by chicagobuss** [comment]
Sure, here's the output:

```
2016-06-07 17:59:02,999 botocore.hooks [DEBUG] Event before-parameter-build.s3.ListObjects: calling handler <function set_list_objects_encoding_type_url at 0x7ff57c55db90>
2016-06-07 17:59:02,999 botocore.hooks [DEBUG] Event before-parameter-build.s3.ListObjects: calling handler <function validate_bucket_name at 0x7ff57c55ccf8>
2016-06-07 17:59:02,999 botocore.hooks [DEBUG] Event before-call.s3.ListObjects: calling handler <function add_expect_header at 0x7ff57c55d1b8>
2016-06-07 17:59:03,000 botocore.endpoint [DEBUG] Making request for OperationModel(name=ListObjects) (verify_ssl=True) with params: {'body': '', 'url': u'http://172.16.1.10:7000/mahbucket?encoding-type=url', 'headers': {'User-Agent': 'Boto3/1.3.1 Python/2.7.10 Linux/4.4.5-15.26.amzn1.x86_64 Botocore/1.4.25'}, 'query_string': {u'encoding-type': 'url'}, 'url_path': u'/mahbucket', 'method': u'GET'}
2016-06-07 17:59:03,000 botocore.hooks [DEBUG] Event request-created.s3.ListObjects: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7ff57b9543d0>>
2016-06-07 17:59:03,000 botocore.auth [DEBUG] Calculating signature using hmacv1 auth.
2016-06-07 17:59:03,000 botocore.auth [DEBUG] HTTP request method: GET
2016-06-07 17:59:03,000 botocore.auth [DEBUG] StringToSign:
GET


Tue, 07 Jun 2016 17:59:03 GMT
/mahbucket
2016-06-07 17:59:03,001 botocore.endpoint [DEBUG] Sending http request: <PreparedRequest [GET]>
2016-06-07 17:59:03,001 botocore.vendored.requests.packages.urllib3.connectionpool [INFO] Starting new HTTP connection (1): 172.16.1.10
2016-06-07 17:59:03,006 botocore.vendored.requests.packages.urllib3.connectionpool [DEBUG] "GET /mahbucket?encoding-type=url HTTP/1.1" 501 None
2016-06-07 17:59:03,007 botocore.parsers [DEBUG] Response headers: {'date': 'Tue, 07 Jun 2016 17:59:30 GMT', 'transfer-encoding': 'chunked', 'server': 'Jetty(9.2.z-SNAPSHOT)'}
2016-06-07 17:59:03,007 botocore.parsers [DEBUG] Response body:
<?xml version="1.0" ?><Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented.</Message><RequestId>4442587FB7D0A2F9</RequestId></Error>
2016-06-07 17:59:03,007 botocore.hooks [DEBUG] Event needs-retry.s3.ListObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x7ff57c0cf690>
2016-06-07 17:59:03,007 botocore.retryhandler [DEBUG] No retry needed.
2016-06-07 17:59:03,007 botocore.hooks [DEBUG] Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x7ff57c55dc08>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 258, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 548, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NotImplemented) when calling the ListObjects operation: A header you provided implies functionality that is not implemented.
```

**Comment by timuralp** [comment]
@chicagobuss I thought this may be an issue where transfer-encoding gets set to `chunked` and the request signature is v2 (where S3 would return the above error), but that doesn't seem to be the case in the query. I can't seem to reproduce this issue by running the same script against master s3proxy and using the filesystem backend. I used boto3 1.3.1 and botocore 1.4.25.

Which backend are you using with the s3proxy?

**Comment by chicagobuss** [comment]
The backend is s3 itself.

I'm also on boto3 1.3.1 and botocore 1.4.25.

I just re-tried with an up-to-date build from master and it worked though - sorry for the noise!
