### ISSUE TITLE
Creating file with Hadoop yields NullPointerException

### ISSUE THREAD

**Issue by eikevons** [andrewgaul/s3proxy#143]
I'm trying to write to s3proxy from Spark (which uses Hadoop) and get the following error:

```
W 06-28 08:06:31.757 S3Proxy-15 o.e.jetty.server.HttpChannel:396 |::] /test-s3-20160628-080610/hadoopKey/_temporary/0/task_201606280806_0000_m_000002/part-00002
java.lang.NullPointerException: null
	at org.jclouds.blobstore.config.LocalBlobStore.maybeQuoteETag(LocalBlobStore.java:938)
	at org.jclouds.blobstore.config.LocalBlobStore.copyBlob(LocalBlobStore.java:540)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy39.copyBlob(Unknown Source)
	at org.gaul.s3proxy.S3ProxyHandler.handleCopyBlob(S3ProxyHandler.java:1548)
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:583)
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

I'm running s3proxy 1.5.0-prerelease in a Docker container. I use the `s3a://` Hadoop-scheme.

The config file contains:
```
s3proxy.authorization=none
s3proxy.endpoint=http://0.0.0.0:2345
jclouds.provider=filesystem
jclouds.identity=identity
jclouds.credential=credential
jclouds.filesystem.basedir=/data/s3proxy
```

The used Dockerfile is
```
FROM java

RUN mkdir /opt/s3proxy
ADD https://github.com/andrewgaul/s3proxy/releases/download/s3proxy-1.5.0-prerelease/s3proxy /opt/s3proxy/s3proxy
RUN chmod +x /opt/s3proxy/s3proxy
WORKDIR /opt/s3proxy
ENTRYPOINT /opt/s3proxy/s3proxy --properties /config/s3proxy.conf
```

**Comment by andrewgaul** [comment]
How do you configure your docker filesystem?  Does it use aufs?  If so this does not support xattr where S3Proxy stores ETags.  I can work around this in jclouds itself.

**Comment by andrewgaul** [comment]
Please test latest master.  You may need to wait an hour or so for jclouds to update its snapshot.

**Comment by eikevons** [comment]
With current master, it is working.

Thanks for the prompt fix!
