### ISSUE TITLE
error for openstack-keystone

### ISSUE THREAD

**Issue by mikewang2016** [andrewgaul/s3proxy#177]
I am trying to use "jclouds.provider=openstack-keystone" to access swift, but get the following exception. I see someone mentioned "swift-keystone", but that's not recognized by s3proxy.

Exception in thread "main" java.lang.IllegalArgumentException: api {id=openstack-keystone, name=OpenStack Keystone Essex+ API, views=[], endpointName=Keystone base url ending in /v${jclouds.api-version}/, identityName=${tenantName}:${userName} or ${userName}, if your keystone supports a default tenant, credentialName=Optional.of(${password}), documentation=http://api.openstack.org/, api=interface org.jclouds.openstack.keystone.v2_0.KeystoneApi} not wrappable as org.jclouds.blobstore.BlobStoreContext; context: org.jclouds.rest.ApiContext<org.jclouds.openstack.keystone.v2_0.KeystoneApi>, views: []
        at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:611)
        at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:595)
        at org.jclouds.ContextBuilder.build(ContextBuilder.java:588)
        at org.gaul.s3proxy.Main.createBlobStore(Main.java:257)
        at org.gaul.s3proxy.Main.main(Main.java:140)

**Comment by clijockey** [comment]
@mikewang2016 did you make any progress with this and get s3proxy to work with Openstack Swift with Keystone?

**Comment by andrewgaul** [comment]
Sorry I missed this earlier -- S3Proxy works with Swift and Keystone although the latter can require configuration.  First you must set the `jclouds.provider=openstack-swift`.  Next you can configure Keystone via additional jclouds properties:

https://github.com/jclouds/jclouds/blob/4bbca9edf943852ce1ea5aa579fa0554f770a3ea/apis/openstack-keystone/src/main/java/org/jclouds/openstack/keystone/v2_0/config/KeystoneProperties.java

The wiki has some examples but not exactly what you want:

https://github.com/andrewgaul/s3proxy/wiki/Storage-backend-examples#softlayer

**Comment by andrewgaul** [comment]
Closing due to lack of activity.  Please reopen if you continue to have issues.
