### ISSUE TITLE
testMultipartSynchronously failing with 'mvn test'

### ISSUE THREAD

**Issue by prakash6061** [andrewgaul/s3proxy#195]
Hello,

I am trying to run `mvn test` but it is failing for following test case :
``JcloudsS3ClientLiveTest>S3ClientLiveTest.testMultipartSynchronously``

Here is the stack trace :
```
Caused by: java.lang.NullPointerException: lastModified
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
        at org.jclouds.s3.domain.ListMultipartUploadResponse.create(ListMultipartUploadResponse.java:38)
        at org.jclouds.s3.xml.PartIdsFromHttpResponseFull.endElement(PartIdsFromHttpResponseFull.java:70)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1776)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2964)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.jclouds.http.functions.ParseSax.doParse(ParseSax.java:140)
        at org.jclouds.http.functions.ParseSax.parse(ParseSax.java:129)
        ... 37 more


Results :

Failed tests:
  JcloudsS3ClientLiveTest>S3ClientLiveTest.testMultipartSynchronously:538 » Runtime
```
This is happening in both mac and windows. I have not changed any src code.
Any suggestions on how to resolve this?
Thanks

**Comment by andrewgaul** [comment]
@prakash6061 I am working on adding some missing metadata to the list parts RPC which caused this regression.  Unfortunately S3Proxy uses a snapshot of jclouds which changed overnight and thus Travis CI could not catch this.
