### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by RaviH** [andrewgaul/s3proxy#196]
I get a NPE when executing the code below for 1.5.1 and 1.5.2:

```
 String endpoint = "http://127.0.0.1:8085";
        URI uri = URI.create(endpoint);
        Properties properties = new Properties();
        properties.setProperty("s3proxy.authorization", "none");
        properties.setProperty("s3proxy.endpoint", endpoint);
        properties.setProperty("jclouds.provider", "filesystem");
        properties.setProperty("jclouds.filesystem.basedir", "/tmp/s3proxy");

        ContextBuilder builder = ContextBuilder
                .newBuilder("filesystem")
                .credentials("x", "x")
                .modules(ImmutableList.<Module>of(new SLF4JLoggingModule()))
                .overrides(properties);
        BlobStoreContext context = builder.build(BlobStoreContext.class);
        BlobStore blobStore = context.getBlobStore();

        S3Proxy s3Proxy = S3Proxy.builder().awsAuthentication(AuthenticationType.AWS_V2, "x", "x").endpoint(uri).keyStore("", "").blobStore(blobStore).build();
        s3Proxy.start();
```

java.lang.NullPointerException
	at org.gaul.s3proxy.S3Proxy.<init>(S3Proxy.java:77)
	at org.gaul.s3proxy.S3Proxy$Builder.build(S3Proxy.java:131)
	at org.gaul.s3proxy.S3Proxy$Builder$build$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at DUMMY$_closure1.doCall(DUMMY.groovy:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:84)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1123)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)

**Comment by andrewgaul** [comment]
@RaviH Odd, this correlates with setting the thread pool name:

```java
((QueuedThreadPool) server.getThreadPool()).setName("S3Proxy");
```

Does your application override the Jetty version?

**Comment by RaviH** [comment]
Thank you so much for helping me with this. 

Yes, it's very possible that I am overriding it. Btw, which Jetty version should I be using.

Also, the problem seems to be the server.setThreadPool() is never called.

**Comment by andrewgaul** [comment]
S3Proxy includes Jetty 9.2.21.v20170120 and I am not sure what overriding it with another version will do.  Jetty should provide a thread pool by default -- does your application do some other configuration of Jetty?
