### ISSUE TITLE
endpoint.getHost() is null for /b2api/v1/b2_list_buckets

### ISSUE THREAD

**Issue by philipp-spiess** [andrewgaul/s3proxy#229]
I'm experiencing issues setting s3proxy with an underlying Backblaze B2 storage for an Arq backup.

Whenever I use an URL like `http://server/bucket_name`, the server logs the following exception:

```
[s3proxy] W 06-03 07:53:37.993 S3Proxy-11 o.e.jetty.server.HttpChannel:396 |::] /<bucket_name>/
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: endpoint.getHost() is null for /b2api/v1/b2_list_buckets
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
        at org.jclouds.b2.blobstore.B2BlobStore.getBucket(B2BlobStore.java:448)
        at org.jclouds.b2.blobstore.B2BlobStore.list(B2BlobStore.java:192)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
        at com.sun.proxy.$Proxy42.list(Unknown Source)
        at org.gaul.s3proxy.S3ProxyHandler.handleBlobList(S3ProxyHandler.java:1254)
        at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:603)
        at org.gaul.s3proxy.S3ProxyHandlerJetty.handle(S3ProxyHandlerJetty.java:70)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: endpoint.getHost() is null for /b2api/v1/b2_list_buckets
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
        at org.jclouds.http.HttpRequest.<init>(HttpRequest.java:245)
        at org.jclouds.rest.internal.GeneratedHttpRequest.<init>(GeneratedHttpRequest.java:83)
        at org.jclouds.rest.internal.GeneratedHttpRequest$Builder.build(GeneratedHttpRequest.java:63)
        at org.jclouds.rest.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:337)
        at org.jclouds.rest.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:137)
        at org.jclouds.rest.internal.InvokeHttpMethod.toCommand(InvokeHttpMethod.java:188)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:84)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy44.listBuckets(Unknown Source)
        at org.jclouds.b2.blobstore.B2BlobStore$1.load(B2BlobStore.java:109)
        at org.jclouds.b2.blobstore.B2BlobStore$1.load(B2BlobStore.java:106)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        ... 22 common frames omitted
```

I've started s3proxy using the Docker build with the following arguments:

```
docker run --publish 80:80 --env S3PROXY_AUTHORIZATION=none --env JCLOUDS_PROVIDER=b2 --env JCLOUDS_IDENTITY=<B2_KEY> --env JCLOUDS_CREDENTIAL=<B2_SECRET> andrewgaul/s3proxy
```

Could this be a bug in JCloud?

**Comment by fwenzel** [comment]
I get the same error with B2.

**Comment by fwenzel** [comment]
Try passing this in: `JCLOUDS_ENDPOINT=https://api.backblaze.com`

**Comment by andrewgaul** [comment]
Sorry for my delayed response; I was traveling all of June.  Thanks @fwenzel for providing a workaround!  The error arose from the Docker image defaulting the endpoint to empty string when S3Proxy expected it to be unset.  I fixed the latter assumption.

**Comment by fwenzel** [comment]
My pleasure!
