### ISSUE TITLE
List all command from s3cmd is listing /tmp as my buckets

### ISSUE THREAD

**Issue by mafrosis** [andrewgaul/s3proxy#39]
It seems calling `s3cmd la` is returning the list of directories in `/tmp` as my bucket list - and subsequently causing an exception because a bucket has an underscore in the name.

Can you take a look at s3tools/s3cmd#474 and see what you think please?

**Comment by andrewgaul** [comment]
@mafrosis Could you share your s3proxy.conf?  It appears that you are using the filesystem blobstore with `jclouds.filesystem.basedir=/tmp` and illegal container names in /tmp.

**Comment by mafrosis** [comment]
You guessed it.. I don't actually know the provenance of this config - it's been sitting around there unused for a while:

    s3proxy.authorization=none
    s3proxy.endpoint=http://127.0.0.1:8880
    jclouds.provider=filesystem
    jclouds.identity=identity
    jclouds.credential=credential
    jclouds.filesystem.basedir=/tmp

**Comment by mafrosis** [comment]
Full stack trace for the `NullPointerException `:

	W 02-04 12:40:21.289 qtp470088803-18 o.e.jetty.server.HttpChannel:398 |::] /host_machine/?delimiter=/
	java.lang.NullPointerException: null
	        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.populateBlobKeysInContainer(FilesystemStorageStrategyImpl.java:457) ~[s3proxy:1.3.0]
	        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.populateBlobKeysInContainer(FilesystemStorageStrategyImpl.java:462) ~[s3proxy:1.3.0]
	        at org.jclouds.filesystem.strategy.internal.FilesystemStorageStrategyImpl.getBlobKeysInsideContainer(FilesystemStorageStrategyImpl.java:169) ~[s3proxy:1.3.0]
	        at org.jclouds.blobstore.config.LocalBlobStore.list(LocalBlobStore.java:211) ~[s3proxy:1.3.0]
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37) ~[s3proxy:1.3.0]
	        at com.sun.proxy.$Proxy38.list(Unknown Source) ~[na:na]
	        at org.gaul.s3proxy.S3ProxyHandler.handleBlobList(S3ProxyHandler.java:640) ~[s3proxy:1.3.0]
	        at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:325) ~[s3proxy:1.3.0]
	        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[s3proxy:1.3.0]
	        at org.eclipse.jetty.server.Server.handle(Server.java:497) ~[s3proxy:1.3.0]
	        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313) ~[s3proxy:1.3.0]
	        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [s3proxy:1.3.0]
	        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [s3proxy:1.3.0]
	        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626) [s3proxy:1.3.0]
	        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546) [s3proxy:1.3.0]
	        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]

**Comment by mafrosis** [comment]
@andrewgaul Glad you got that cleared up :)

Can I conclude that the following should be removed from my config? Is there any reason for using such a construct?

    jclouds.filesystem.basedir=/tmp

**Comment by andrewgaul** [comment]
I am not sure why you saw a `NullPointerException`, whether the directly had some broken symlink or some other issue, but the jclouds code should handle this.  Upstream should release jclouds 1.9.0 including this fix in a few weeks then I will run another S3Proxy release.  In the mean-time you can compile your own binary from the instructions in README.md.

You need to set `jclouds.filesystem.basedir` to some valid path since this is where S3Proxy will store the underlying objects when using the filesystem blobstore.  /tmp is not a good value if this data needs to persist since some Linux distributions clear it out on reboot.

**Comment by mafrosis** [comment]
I see, thanks. I'll make `jclouds.filesystem.basedir` an empty directory especially for `s3proxy`'s use. Using `/tmp` was how we ended up with buckets with underscores in the name.

Good to catch a couple of edge cases in both `jclouds` and `s3cmd` though! Thanks for your help.
