### ISSUE TITLE
not authorized for swift and openstack-swift for softlayer object store backend

### ISSUE THREAD

**Issue by dleute** [andrewgaul/s3proxy#82]
I am attempting to connect s3 proxy to a softlayer object storage which should be equivalent to swift 2.2.

Pasted below is the error with the swift provider (removed auth string, replaced with ****)

I am using current master for this exercise. This first error is after successfully putting a file and then trying to get the same exact file.

Any help would be appreciated. Should I revert to a previously tagged release?

```
org.jclouds.rest.AuthorizationException: command: GET https://dal05.objectstorage.softlayer.net/v1/AUTH_****/container_0/ HTTP/1.1 failed with response: HTTP/1.1 401 Unauthorized; content: [<html><h1>Unauthorized</h1><p>This server could not verify that you are authorized to access the document you requested.</p></html>]
	at org.jclouds.openstack.swift.handlers.ParseSwiftErrorFromHttpResponse.handleError(ParseSwiftErrorFromHttpResponse.java:58) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:136) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:105) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.rest.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at com.sun.proxy.$Proxy51.invoke(Unknown Source) ~[na:na]
	at org.gaul.s3proxy.S3ProxyHandler.doHandleAnonymous(S3ProxyHandler.java:561) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:294) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.gaul.s3proxy.S3ProxyHandler.handle(S3ProxyHandler.java:237) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) ~[s3proxy-original:1.5.0-SNAPSHOT]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [s3proxy-original:1.5.0-SNAPSHOT]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [s3proxy-original:1.5.0-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [s3proxy-original:1.5.0-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [s3proxy-original:1.5.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
```

For kicks I tried it with the openstack-swift provider and got this on startup:

```
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: org.jclouds.http.HttpResponseException: command: POST https://dal05.objectstorage.softlayer.net/auth/v1.0/tokens HTTP/1.1 failed with response: HTTP/1.1 400 Bad Request; content: [<html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at org.jclouds.openstack.keystone.v2_0.config.KeystoneAuthenticationModule$2.get(KeystoneAuthenticationModule.java:252)
	at org.jclouds.openstack.keystone.v2_0.config.KeystoneAuthenticationModule$2.get(KeystoneAuthenticationModule.java:249)
	at org.jclouds.openstack.keystone.v2_0.suppliers.LocationIdToURIFromAccessForTypeAndVersion.get(LocationIdToURIFromAccessForTypeAndVersion.java:94)
	at org.jclouds.openstack.keystone.v2_0.suppliers.LocationIdToURIFromAccessForTypeAndVersion.get(LocationIdToURIFromAccessForTypeAndVersion.java:54)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
	at org.jclouds.suppliers.SupplyKeyMatchingValueOrNull.get(SupplyKeyMatchingValueOrNull.java:52)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedBlobStoreContext.getBlobStore(RegionScopedBlobStoreContext.java:122)
	at org.gaul.s3proxy.Main.main(Main.java:131)
```

**Comment by dleute** [comment]
Conf file (with auth details blanked out)

s3proxy.authorization=none (using none to eliminate hurdles, but creates other problems)
s3proxy.endpoint=http://****:8080
jclouds.provider=swift
jclouds.endpoint=https://dal05.objectstorage.softlayer.net/auth/v1.0/
jclouds.identity=****
jclouds.credential=****

**Comment by andrewgaul** [comment]
@dleute Can you test again setting `jclouds.provider=openstack-swift` and adding `jclouds.keystone.credential-type=tempAuthCredentials`?

**Comment by dleute** [comment]
This may have just fixed every problem I have. Is this documented somewhere?

I'll test for the next few days and get back to you!

Thanks for the response!

**Comment by andrewgaul** [comment]
Could you add an example to the wiki once you verify a working configuration:

https://github.com/andrewgaul/s3proxy/wiki/Provider-examples

Thanks!

**Comment by dleute** [comment]
Done! Closing this issue for now.
