### ISSUE TITLE
s3cmd error because s3proxy does not return etag

### ISSUE THREAD

**Issue by dleute** [andrewgaul/s3proxy#83]
It looks like s3proxy doesn't return an etag which makes it difficult to use s3cmd with the proxy. Obviously any other client that uses the etag will also have issues.

This is on a s3cmd get s3://container_0/file.txt based on a swift provider.

I am receiving this error:

```
Problem: KeyError: 'etag'
S3cmd:   1.6.0+
python:   2.7.10 (default, Oct  6 2015, 11:07:59) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/s3cmd-1.6.0_-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2813, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/s3cmd-1.6.0_-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2721, in main
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/s3cmd-1.6.0_-py2.7.egg/EGG-INFO/scripts/s3cmd", line 549, in cmd_object_get
  File "build/bdist.macosx-10.11-x86_64/egg/S3/S3.py", line 636, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "build/bdist.macosx-10.11-x86_64/egg/S3/S3.py", line 1455, in recv_file
    md5_from_s3 = response["headers"]["etag"].strip('"')
KeyError: 'etag'
```

**Comment by andrewgaul** [comment]
@dleute I tested this using a SoftLayer backend and s3cmd 1.5.0 and master (e4639e0862ae04d348f127a96e09c1846bb20208) and cannot reproduce your symptoms.  Can you give me more information on which backend and client you are using?  Also re-run with debug logging to see what the backend provides via:

```
java -DLOG_LEVEL=debug -jar target/s3proxy --properties configs/softlayer.conf
```

**Comment by dleute** [comment]
I think this is because of my previous issue using the swift legacy provider. With your feedback for openstack-swift it is now working as expected.

I'll test for a bit and comment!

Thanks!

**Comment by dleute** [comment]
This issue was related to #82 and has been resolved along with that issue.

Thanks for the help!

**Comment by andrewgaul** [comment]
Thanks for the feedback on the legacy `swift` provider.  jclouds replaced this with the modern `openstack-swift` provider which has many improvements but retained the legacy provider since HP still uses it.

**Comment by dleute** [comment]
Yep. I was aware. I just wasn't aware of the temp credentials to make it work with v1.0 auth. Does jclouds itself have documentation on the config parameters like that? I haven't found any yet.
